Repository abhiTronix/vidgear, pull requests merged in 2019-07, with the labels that each got.

#27 Enhancement: Introducing ScreenGear, that enables multithreaded Live Screen Cast support in vidgear
  .travis.yml
  scripts/bash/install_opencv.sh
  setup.py
  vidgear/gears/__init__.py
  vidgear/gears/camgear.py
  vidgear/gears/helper.py
  vidgear/gears/pigear.py
  vidgear/gears/screengear.py
  vidgear/gears/writegear.py
  vidgear/tests/writer_tests/test_IO.py
  vidgear/version.py
Labels: enhancement, in progress

#31 Enhancement: Introducing NetGear: synchronous video frames transferring between interconnecting systems over the network
  scripts/bash/install_opencv.sh
  scripts/bash/prepare_dataset.sh
  setup.py
  vidgear/gears/__init__.py
  vidgear/gears/netgear.py
  vidgear/gears/screengear.py
  vidgear/tests/videocapture_tests/test_camgear.py
  vidgear/version.py
Labels: enhancement, in progress

#32 Enhancement: Revamp and Modernize Documentation
  README.md
  changelog.md
  contributing.md
Labels: enhancement, in progress

#33 Enhancement: New Project Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  setup.py
  vidgear/gears/screengear.py
Labels: enhancement, in progress

#34 Enhancement: Sponsor Button
  .github/FUNDING.yml
  README.md
  changelog.md
Labels: enhancement, in progress

#35 Finalizing v0.1.5 Release: Bug Fixes & Updates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  README.md
  appveyor.yml
  contributing.md
  scripts/bash/install_opencv.sh
  setup.py
  vidgear/gears/camgear.py
  vidgear/gears/helper.py
  vidgear/gears/netgear.py
  vidgear/gears/pigear.py
  vidgear/gears/screengear.py
  vidgear/gears/stabilizer.py
  vidgear/gears/videogear.py
  vidgear/gears/writegear.py
  vidgear/tests/benchmark_tests/fps.py
  vidgear/tests/benchmark_tests/test_benchmark_Videocapture.py
  vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
  vidgear/tests/benchmark_tests/test_benchmark_playback.py
  vidgear/tests/test_helper.py
  vidgear/tests/videocapture_tests/test_camgear.py
  vidgear/tests/videocapture_tests/test_videogear.py
  vidgear/tests/writer_tests/test_IO.py
  vidgear/tests/writer_tests/test_compression_mode.py
  vidgear/tests/writer_tests/test_non_compression_mode.py
  vidgear/version.py
Labels: bug, enhancement, in progress

#17 VidGear v0.1.5 Release
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  README.md
  appveyor.yml
  changelog.md
  contributing.md
  scripts/bash/install_opencv.sh
  scripts/bash/prepare_dataset.sh
  setup.py
  vidgear/gears/__init__.py
  vidgear/gears/camgear.py
  vidgear/gears/helper.py
  vidgear/gears/netgear.py
  vidgear/gears/pigear.py
  vidgear/gears/screengear.py
  vidgear/gears/stabilizer.py
  vidgear/gears/videogear.py
  vidgear/gears/writegear.py
  vidgear/tests/benchmark_tests/fps.py
  vidgear/tests/benchmark_tests/test_benchmark_Videocapture.py
  vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
  vidgear/tests/benchmark_tests/test_benchmark_playback.py
  vidgear/tests/test_helper.py
  vidgear/tests/videocapture_tests/test_camgear.py
  vidgear/tests/videocapture_tests/test_videogear.py
  vidgear/tests/writer_tests/test_IO.py
  vidgear/tests/writer_tests/test_compression_mode.py
  vidgear/tests/writer_tests/test_non_compression_mode.py
  vidgear/version.py
Labels: New Release, Solved

#39 Remove duplicate code to import MSS
  vidgear/gears/screengear.py
Labels: enhancement, exemplary :trophy:, in progress

#42 [Enhancement] Adding OSX environment support for Travis Cli tests
  .travis.yml
  appveyor.yml
  scripts/bash/prepare_dataset.sh
  vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
  vidgear/tests/benchmark_tests/test_benchmark_playback.py
  vidgear/tests/test_helper.py
  vidgear/tests/videocapture_tests/test_camgear.py
  vidgear/tests/writer_tests/test_compression_mode.py
  vidgear/tests/writer_tests/test_non_compression_mode.py
Labels: enhancement, in progress
