Repository abhiTronix/vidgear, pull requests merged in 2020-01, with the labels that each got.

#88 Undefined name: 'self'. 'logger' defined on line 62
  vidgear/gears/helper.py
Labels: Bug :beetle:, In progress :construction:, Priority Critical :red_circle:

#90 Development
  vidgear/gears/helper.py
Labels: Bug :beetle:, In progress :construction:, Maintenance :building_construction:, New Release :cookie:

#91 Travis CI: Run flake8 to find undefined names
  .travis.yml
Labels: Enhancement :new:, In progress :construction:, Maintenance :building_construction:

#93 Fixes for flake8 Tests
  changelog.md
  vidgear/gears/screengear.py
  vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
  vidgear/tests/videocapture_tests/test_camgear.py
Labels: Bug :beetle:, In progress :construction:

#95 Code Maintenance: Logging Updates
  README.md
  codecov.yml
  vidgear/gears/camgear.py
  vidgear/gears/helper.py
  vidgear/gears/netgear.py
  vidgear/gears/pigear.py
  vidgear/gears/screengear.py
  vidgear/gears/stabilizer.py
  vidgear/gears/videogear.py
  vidgear/gears/writegear.py
  vidgear/tests/benchmark_tests/test_benchmark_Videocapture.py
  vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
  vidgear/tests/benchmark_tests/test_benchmark_playback.py
  vidgear/tests/network_tests/test_netgear.py
  vidgear/tests/test_helper.py
  vidgear/tests/videocapture_tests/test_camgear.py
  vidgear/tests/videocapture_tests/test_screengear.py
  vidgear/tests/videocapture_tests/test_videogear.py
  vidgear/tests/writer_tests/test_compression_mode.py
  vidgear/tests/writer_tests/test_non_compression_mode.py
Labels: Enhancement :new:, In progress :construction:, Maintenance :building_construction:

#98 Enhancement: Introducing WebGear - A powerful ASGI Video-streamer API
  .travis.yml
  README.md
  appveyor.yml
  changelog.md
  codecov.yml
  scripts/bash/prepare_dataset.sh
  setup.py
  vidgear/gears/__init__.py
  vidgear/gears/__main__.py
  vidgear/gears/helper.py
  vidgear/gears/pigear.py
  vidgear/gears/stabilizer.py
  vidgear/gears/videogear.py
  vidgear/gears/webgear.py
  vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
  vidgear/tests/network_tests/test_netgear.py
  vidgear/tests/network_tests/test_webgear.py
  vidgear/tests/test_helper.py
  vidgear/tests/videocapture_tests/test_camgear.py
  vidgear/tests/videocapture_tests/test_videogear.py
Labels: Bug :beetle:, Enhancement :new:, In progress :construction:, Maintenance :building_construction:

#101 CLI Maintenance Updates and bugfixes
  README.md
  changelog.md
  vidgear/gears/__main__.py
  vidgear/gears/camgear.py
  vidgear/gears/helper.py
  vidgear/gears/netgear.py
  vidgear/gears/pigear.py
  vidgear/gears/screengear.py
  vidgear/gears/videogear.py
  vidgear/gears/webgear.py
  vidgear/gears/writegear.py
  vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
  vidgear/tests/network_tests/test_netgear.py
  vidgear/tests/network_tests/test_webgear.py
  vidgear/tests/test_helper.py
  vidgear/tests/videocapture_tests/test_camgear.py
  vidgear/tests/videocapture_tests/test_screengear.py
  vidgear/tests/videocapture_tests/test_videogear.py
  vidgear/tests/writer_tests/test_IO.py
  vidgear/tests/writer_tests/test_compression_mode.py
  vidgear/tests/writer_tests/test_non_compression_mode.py
Labels: Bug :beetle:, In progress :construction:, Maintenance :building_construction:
